### ISSUE TITLE
[Client] LB across multiple endpoints?

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#3]
Should a Client proxy be able to send packets to multiple Server proxy endpoints, probably in some sort of load balancer way - such as round robin, or random manner?

This provides another layer of redundancy in case a singular Server proxy goes down, and it takes time to realise and move to a new one. At least this way, some traffic is going through -- but seemingly at a slightly lower latency.

Maybe a configuration like:

```yaml
local:
  port: 7000 # the port to receive traffic to locally
client:
  connection_id: 1x7ijy6 # the connection string to attach to the traffic
  lb_policy: ROUND_ROBIN # load balance policy. Round Robin / Random / ???
  endpoints:
    -  127.0.0.1:7001 # the address to send traffic to
    -  127.0.0.1:7002
    -  127.0.0.1:7003
```
