### ISSUE TITLE
Add support for version based packet processing

### ISSUE THREAD

**Issue by iffyio** [googleforgames/quilkin#401]
The problem

The CaptureBytes filter is currently the primary means in quilkin to extract information from packets. Packets have a fixed format that determines where to find that info. In practice however that format can change over time or differ between packets - as a result it would be desirable to capture (potentially different) info based on the format of the particular packet in question.

For context, we're currently trying out UnrealEngine integration where the client tags each packet with a routing token but we can't actually put this in production unless we have a backwards compatibilty plan in place otherwise we'll probably have to run specific proxies with different filter chains for our different clients over time to avoid breaking old clients whenever we add changes to the packet format.
We'd also like to use the same set of proxies to handle packets across all our games and not necessarily be tied to having them all use the same packet format.

For example, right now due to some UE limitations, we need to tag our token onto packets as a prefix but we hope to resolve this upstream in the future and then switch to appending the token as a suffix instead. Also, today we only send a routing token but we might want to include more information later on - like when we add support for setting up a connection/authentication.
In any case, we don't want to break previous clients that only use a prefixed token.

Proposal

I think we can extend the CaptureBytes filter to
1. be _version aware_ (i.e know that a packet has a version)
2. capture multiple pieces of information from a packet (currently it can only extract a single piece of info) -

by configuring the filter to first, fetch version information either from the packet itself or from dynamic metadata - and then based on the value of that found version, execute a list of captures.
We should also have support for what to do if the version we got doesn't have any registered list of captures - allow the packet or drop the packet, the former lets us bypass the filter for packets that do not need to be processed by it (e.g some version x packet has no interesting info for the filter to capture).

config wise the filter's schema becomes something like:

```yaml
# The config is one of:
config:
  # A versioned, capture list
  versioned: versioned
  # Short hand for a non-versioned, capture list of 1 - which is how is works today.
  capture: capture
  # A list of captures to perform, non-versioned.
  captures: [ capture ]
```

```yaml
versioned:
  # Where to retrieve what version to use.
  # For each packet the version is always retrieved first.
  version: version
  # A list of (version, captures) pair checked in list order to figure out what capture list
  # to use.
  captures: [ versionedCapture ]
  # What to do if we don't find a capture list to process the packet with.
  onNoVersionMatched: DROP | PASSTHROUGH
```

```yaml
# Version is retrieved from one of
version:
  # A capture from the packet
  packet: capture
  # Or from dynamic metadata (e.g in cases where you have multiple CaptureByte
  # filters in the chain or the version is already known from some other means).
  metadataKey: string
```

```yaml
versionedCapture:
  # If the captured version matches this value
  version: base64Bytes
  # then use this list to capture info from the packet.
  captures: [ capture ]
```

```yaml
# This part remains largely the same as today.
capture:
  strategy: PREFIX | SUFFIX
  # This becomes optional - for cases where we don't necessarily want to store the
  # captured value (like the version maybe could only be captured and thrown away after usage)
  metadataKey: string
  size: int
  remove: bool
```

As an example configuration, the following shows a CaptureBytes that has evolved over time and is backwards compatible with older clients+packet formats.
```yaml
config:
  versioned:
    version:
      packet:
        strategy: PREFIX
        size: 1
        metadataKey: packet-version
        remove: true
    captures:

    # v0 has only a single token prefix
    - version: AA==
      captures:
      - strategy: PREFIX
        size: 16
        metadataKey: routing-token
        remove: true

    # In v1 the token is now a suffix
    - version: AQ==
      captures:
      - strategy: SUFFIX
        size: 16
        metadataKey: routing-token
        remove: true

    # In v2 we have both a token and some other piece of information attached
    - version: Ag==
      captures:
      # First capture the routing token
      - strategy: SUFFIX
        size: 16
        metadataKey: routing-token
        remove: true
      # Then capture the extra info
      - strategy: SUFFIX
        size: 32
        metadataKey: extra-info
        remove: true
```

**Comment by markmandel** [comment]
Oooh this is very interesting. I can totally understand this use case for sure.

To me - the versioning makes perfect sense. The only thought I had is - that we likely will want versioning across different filters (say you want to change compression or encryption between versions?) - so my concern therefore would be that the above design has a tight coupling to CaptureBytes.

This could potentially also be done as two seperate Filter configurations (something like):

```yaml
version: v1alpha1
static:
  filters:
    - name: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes
      config:
        strategy: PREFIX
        size: 1
        metadataKey: packet-version
        remove: true
    - name: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes
      config:
         versionMetadataKey: packet-version
         versions:
            # v0 has only a single token prefix
            - version: AA==
              captures:
              - strategy: PREFIX
                size: 16
                metadataKey: routing-token
                remove: true
  endpoints:
    - address: 127.0.0.1:7001
```

Another question: Do we also need a "if it's this version do nothing/passthrough?" (if we did that, we probably wouldn't need a single Filter to capture multiple pieces of data, we could have multiple CaptureBytes Filter configurations in the chain)

I'm personally more inclined towards a Filter does one thing not multiple operations, just because I think it's easier to mentally get a picture of what is going on - but it is a more verbose configuration.

Another fun thought: Should this versioning be a general part of our overall configuration somehow (We may run into xDS compatibility issues here?) Or a standard part of all our Filter configs somehow? (or maybe just a useful library for when needed). This feels to me like versioning would be extremely useful!

**Comment by iffyio** [comment]
> Another fun thought: Should this versioning be a general part of our overall configuration somehow (We may run into xDS compatibility issues here?) Or a standard part of all our Filter configs somehow? (or maybe just a useful library for when needed).

Yes, I think this is the proper way to go. I went with a CaptureBytes only solution since that's the only way we can get info from a packet today but I think this is the better alternative to properly support other versioning for other filters.
So in my mind what this requires is that we'll have one filter chain per version vs our single filter chain today.
Then quilkin itself needs to know where the version comes from (it can't really be a filter since then there's the chicken and egg problem) but it should be enough to say, _capture these bytes from all packets to get the version_.
XDS wise this all works (it supports multiple filter chains, and the concept of a filterchain match to select a filter chain based on some equality check).

> Another question: Do we also need a "if it's this version do nothing/passthrough?" (if we did that, we probably wouldn't need a single Filter to capture multiple pieces of data, we could have multiple CaptureBytes Filter configurations in the chain)

Yeah, the pass through option is required if we have some packet version that doesn't have any info to capture (whereas some other versions do).
Note that only supporting a single capture per filter won't work with versioning like in your example, e.g if we have a v1 filter too, what does the v0 filter do when it receives a v1 packet?
Neither of these are an issue or needed if we go the multiple filter chain route though.

> I'm personally more inclined towards a Filter does one thing not multiple operations, just because I think it's easier to mentally get a picture of what is going on - but it is a more verbose configuration.

I think it makes more sense for capturebytes to support multiple operations, (which would be a separate issue if we go down the multiple filter chain route since it becomes unrelated to version).
It's surely the less verbose alternative compared to using multiple filters because it'll literally contain the exact same list of captures without the boilerplate of a full filter specification per capture.
But more importantly, filters aren't free (there's a difference between running 1 Noop filter vs running 5 Noop filters in terms of perf) - if one feels a capture per filter is fine then they can still do that in their config.
I think this is similar to typical unix commands like grep, sed etc, it'll be silly if we were required to do `sed s/.../ | sed s/.../`  without any means to group all transformations into the same sed/grep command. The filter is still doing one thing (capturing bytes) but now it'll do it well :)

**Comment by markmandel** [comment]
> Yes, I think this is the proper way to go. I went with a CaptureBytes only solution since that's the only way we can get info from a packet today but I think this is the better alternative to properly support other versioning for other filters.

I think that 100% make sense.

> XDS wise this all works (it supports multiple filter chains, and the concept of a filterchain match to select a filter chain based on some equality check).

Oh that's neat! I really need to dig into those protos more.

Is this the one you are referring to: 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchainmatch

Is there an issue here in that a `FilterChainMatch` doesn't allow us to specify our own config through our own UDP specific configuration? 🤔 

> Then quilkin itself needs to know where the version comes from (it can't really be a filter since then there's the chicken and egg problem) but it should be enough to say, capture these bytes from all packets to get the version.

Sound like we need something similar to `FilterChainMatch` - that can introspect a packet for specific data before it goes into a FilterChain.

> I think it makes more sense for capturebytes to support multiple operations, (which would be a separate issue if we go down the multiple filter chain route since it becomes unrelated to version).
> But more importantly, filters aren't free (there's a difference between running 1 Noop filter vs running 5 Noop filters in terms of perf) - if one feels a capture per filter is fine then they can still do that in their config.

The perf aspect sold me on multiple operations per filter. 👍🏻 SGTM.

**Comment by iffyio** [comment]
Sounds good!

> Is this the one you are referring to:
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchainmatch
>
> Is there an issue here in that a FilterChainMatch doesn't allow us to specify our own config through our own UDP specific configuration? 

Yes that's the one, there's the `application_protocols` field that is likely the most relevant in our case - we can specify the version(s) in that list to match against in order to select the filter chain. The `FilterChainMatch` is part of the `FilterChain` resource (currently its always ignored by Quilkin) so it should be enough to pass any info in there for that filter chain and have Quilkin pick it up.

**Comment by markmandel** [comment]
> Yes that's the one, there's the application_protocols field that is likely the most relevant in our case 

Just so I can think this through as a use case: Say version is defined as a 1st byte in a packet. (So we max at 256 versions)

How would we configure that through the `application_protocols`? 🤔 

Unfortunately we can't do our own configuration system, so we would have a set of enum values for `application_protocols`?

So `prefix_byte` could be the option for above, and we might also have the option of `suffix_byte` if someone wanted to have the version be the last byte value?

If for some reason people wanted to use a different strategy, they might need to define their own FilterChainMatch implementation? (or say, use two bytes... which seems unlikely, since why would you need more than 256 versions?)

Is that the general gist you were thinking?

**Comment by iffyio** [comment]
Ah so what I meant was that `application_protocols` will contain the versions to match the filter chain only, it doesn't say anything about where the version to compare against come from, that one is set on startup to e.g prefix, suffix etc, and it can't change dynamically (since that property can't change between versions either)

- so on the xds side, we get something like this from the management server

```yaml
# simplified proto
filter_chains: [
  {
    filter_chain_match: {
      application_protocols: ["AA=="] # v0
    },
    filters: [...] # Use this filter chain to process any v0 packets
  },
  {
    filter_chain_match: {
      application_protocols: ["AQ==", "Ag=="] # v1 and v2
    },
    filters: [...] # Use this filter chain to process any v1 or v2 packets.
  },
]
```
Then Quilkin itself is configured with how to capture the version, it applies to all packets
```yaml
version: v1alpha1
dynamic:
  filter_chain:
    versioned:
      capture_version:
        strategy: PREFIX
        size: 1
```

For static configs
```yaml
version: v1alpha1
static:
  # We can support one of 'filter_chain' or 'filters' so that 'filters' is short hand for
  # a non versioned filter chain as it is today.
  filter_chains:
    # One of 'versioned' or 'non_versioned'
    versioned:
      capture_version:
        strategy: PREFIX
        size: 1

      filter_chain:
      - versions: [ AA== ]
        filters:
        - name: quilkin.extensions.filters.debug.v1alpha1.Debug
      - versions: [ Ag== ]
        filters:
        - name: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes
```

For each packet, quilkin uses the provided static info under `capture_version` to get the packet's version, then depending on static vs dynamic config, looks for a match of the captured bytes in the static `versions` or dynamic `application_protocols` list to select a filter chain

**Comment by markmandel** [comment]
Got it, got it, got it, got it! That makes perfect sense to me. I like it!

**Comment by XAMPPRocky** [comment]
Sorry, only just reading through this now. I'm a bit concerned that this is adding a lot of complexity for not a lot of benefit. This comes pretty close to writing code as a configuration. I think we should take a step back and look at the problem as whole and think about what we're achieving with this feature rather than trying to shove this functionality into the current filters.

The problem statement as I see it, is that we have a custom user-specific protocol that we want to parse with Quilkin which can't be upstreamed. That protocol is complex, so we need a way to provide Quilkin with functionality to parse and validate that protocol. I don't think we should do that by adding parsing to Quilkin's configuration format. This versioning scheme is really just lookahead, there's protocols where this simple lookahead won't work. Adding parsing significantly increases the problem space the configuration needs to cover immensely and is a problem that is better handled in code, where you can use your own libraries and conditionals to parse the protocol.

This kind of custom behaviour is exactly why we have the `Filter` trait though, so we should look at what currently makes it undesirable to write a custom filter to handle this behaviour. To me it boils down two main parts, both of which have to do with the current rigidity in Quilkin's extensibility.

- No scripting filter. Even with just WASM, it would be less code (~10x comparing #412 to #256) for Quilkin, and the users to write this protocol as a WASM script than a YAML file.
- There's no way to extend Quilkin, without **also** distributing your own Quilkin binary. No one is going to do it, as evident by the fact that doing this would have been the most performant and quickest option here, and even we didn't do it. If the filter traits were moved to another crate, filters could be defined in separate crates and loaded by Quilkin at runtime. That would be much more reasonable for users.

To me, implementing either of those alternatives, and implementing the UE protocol as a separate crate is much more preferable to me than adding a versioning scheme that makes our configuration more complicated.

**Comment by iffyio** [comment]
I'm not sure I'm following the idea with filters. Could you give an example of how your proposal solves the problems that the ticket addresses e.g if formats change between clients such that different packet formats should be handled by different set of filters?

**Comment by markmandel** [comment]
> This versioning scheme is really just lookahead, there's protocols where this simple lookahead won't work.

I can't think of any, do you have an example at hand? Be good to have a reference so we can cover the use case if it is common.

> There's no way to extend Quilkin, without also distributing your own Quilkin binary. No one is going to do it, as evident by the fact that doing this would have been the most performant and quickest option here, and even we didn't do it. If the filter traits were moved to another crate, filters could be defined in separate crates and loaded by Quilkin at runtime. That would be much more reasonable for users.

While I think being able to dynamically load Filters from a core Quilkin binary would be definitely awesome (big thumbs up on this as an idea, we should definitely have this as a ticket 👍🏻 ), I don't think I agree with the original premise -- given that we have people in the community doing this right now for their own custom Filters. But I'm 100% for easier extensibility for sure.

> You would have a "UnrealProtocol" filter, which would contain the parsing logic for the protocol data unit, instead of trying to have this functionality in CaptureBytes. What is being described is parsing logic which is better described in code IMO.

🤔 say we had the ability to create a `MyCustomGameProtocol` Filter to be able to determine which version is running - how does the Filter tell Quilkin which version of the config to use, and pass that through to a Filter Chain? I'm not quite following from the example code above.

Envoy does has the concept of [FilterChainMatch](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchainmatch) to solve this issue's problem, and it has a few options to do equality against a Filter Chain version -- I'm wondering that (probably not for this PR, since it's pretty big right now), we need to:

* Have several core `FilterChainMatch` implementations to a trait
  * Maybe specified by `transport_protocol` in xDS (since it's a string value).
  * To start: `Prefix`, `Suffix`, and we can expand common use cases over time.
* Default FilterChainMatch is checking the byte `Prefix`.
* Allow people to write their own and register them also with the system? (Which would also lead us to being able to dynamically link in Filter trait implementations as you described above).

WDYT?

**Comment by XAMPPRocky** [comment]
> Filter to be able to determine which version is running - how does the Filter tell Quilkin which version of the config to use, and pass that through to a Filter Chain? I'm not quite following from the example code above.

Well first I think about what we’re using the version for. Right now as described the version isn’t being used for anything but changing how the capture works, and that parsing code belongs in the GameProtocol filter.

> Envoy does has the concept of FilterChainMatch to solve this issue's problem, and it has a few options to do equality against a Filter Chain version

I think having a “match” filter would solve this problem, but that’s different from versioning. If we had a match filter that could match against dynamic metadata, then you could have GameProtocol set the version in the metadata. Something like the following but maybe a different syntax for the match filter.


```yaml

version: v1alpha1
static:
  filters:
    # Added as a crate, building our own Quilkin version, or written as a script.
    - name: embark.extensions.GameProtocol
    - name: quilkin.match
      config:
        metadata: embark.GameProtocol.version
        match_arms:
        - value: 1
          then:
           - name: quilkin.compress
```

**Comment by iffyio** [comment]
> Right now as described the version isn’t being used for anything but changing how the capture works

This isn't correct. I think the version here could be seen as an implementation detail here (e.g the `UnrealProtocol` filter mentioned here sounds similar to the extended `CaptureBytes` earlier in this ticket). Its not trying to parse any protocol so it doesn't care whether Protocol buffers or ASN.1 etc is being used.

The problem is how do we ensure we don't break clients when we send new/different-but-supported types of packets.

What happens when a user goes from sending Protocol buffers to ASN.1 (with or without encryption/authentication etc), what would a filter chain look like that supports both formats and possible combinations look like?
For example, initially they'd start with a filter chain `ProtocolBuffer -> CaptureBytes -> TokenRouter`, then after adding encryption it might look like `Decrypt -> ProtocolBuffer -> CaptureBytes -> TokenRouter` but then what happens when older clients send a non-encrypted packet to this new filter chain? or what would the new filter chain look like to accomodate both client types?

This is the issue we're looking to solve. The current solution is that we keep both filter chains around and the user appends a packet version that tells us which filter chain to use i.e they can make arbitrary changes compatible as long as they have a filter chain that accepts the new packet types.

What I didn't follow is, how does the the alternative being proposed solve this issue? If we use the `ProtocolBuffer -> ...` filter chain scenario I've described as an example, what bits do we need in place and what would they do?

**Comment by iffyio** [comment]
> ASN.1 and Protocol Buffers are data formats for defining protocols not protocols themselves, and switching between the two is a breaking change, and there's no way you can make that not breaking change

How do you mean there's no way to not make it a breaking change, the current version implementation does just that? So my thinking is that this behavior should be similar to what envoy does in that it can handle with several protocols at once - you can use the same proxy to handle anything from tcp, udp, http, grpc, mongodb etc traffic.

> Is your question how do you have a backwards compatible protocol that is optionally encrypted

No, encryption was an example here the idea covers arbitrary optional features.

Is the proposal then that we'd have some Quilkin protocol (which may or may not be an existing protocol like SRT), then implement things like encryption, authentication, compression etc in that protocol? My understanding was that those things are to be handled by filters. Or is it something like our protocol implementation would flag in dynamic metadata which features are on/off and we can still have filters that are conditionally active in the chain?

**Comment by iffyio** [comment]
Ah I see,

> Yes, exactly. But Envoy doesn't implement these protocols as chains of filters, the protocols are implemented as single units

What I meant is that you can have an envoy proxy that can handle e.g both udp and grpc _at the same time_ and that is implemented as separate filter chains. But maybe we don't have to be that flexible and only ask users to bring their own custom filter.

> How is implementing that protocol inside a filter, it not being handled by a filter?

I meant implementing it all (encryption etc) in the game protocol filter vs individual filters.

> a "match" filter, that accepts input and chooses a list of filters

Oh but this requires nesting filters right?

I _think_ I get the idea now, iiuc a user will bring their own filter (or use an already existing one) that does some initial packet parsing according to some protocol (which really shouldn't change), then that filter flags in dynamic metadata how the packet should be processed (like encryption on/off) for further filters in the chain to use. Is this description correct?
I think i'd be okay with whatever route we go with

**Comment by XAMPPRocky** [comment]
> What I meant is that you can have an envoy proxy that can handle e.g both udp and grpc at the same time and that is implemented as separate filter chains. But maybe we don't have to be that flexible and only ask users to bring their own custom filter.

I mean there's nothing preventing this from still being the case, I just think that's different from versioning. You could have a match filter that delegates to a UDP and gRPC filter.

> I meant implementing it all (encryption etc) in the game protocol filter vs individual filters.

Yeah, I've been mainly meaning having it in a single filter. Maybe the protocol was truly simple enough that you could write it as a filter chain, but I think the moment there's a lot of conditionals based on data, that's the point to take it inside a filter.

> Oh but this requires nesting filters right?

Yes, but there shouldn't be issue with that. You can nest filters inside filters in both YAML and Rust no problem.

> I think I get the idea now, iiuc a user will bring their own filter (or use an already existing one) that does some initial packet parsing according to some protocol (which really shouldn't change), then that filter flags in dynamic metadata how the packet should be processed (like encryption on/off) for further filters in the chain to use. Is this description correct?

Yes this is what I mean 100%. It's the job of the "GameProtocol" filter IMO to parse the packet data and make it "Quilkin aware" through things like dynamic metadata, that other filters can then take advantage of.

**Comment by XAMPPRocky** [comment]
> I feel like I'm coming back to FilterChainMatch, but to come back to @XAMPPRocky 's original point - do we actually want to be able to handle different UDP protocols through Quilkin? Or do is each proxy only going to handle a single protocol with multiple versions?

I feel like we do want to be able to handle protocols built onto of UDP, I just think that the protocol parsing should be a filter and not a filter chain. It needs to be a complete logical unit because parsing is complex and depending on the protocol how it is parsed could have security implications (e.g. needing constant time comparisons in your decryption code). So it's something that we should have in code, and be able to take advantage of Rust's features.

The protocol filter's job is to take the protocol, and make Quilkin aware of it and able to act smartly on the data. So this would be for example populating metadata with header information such as the version so filters can trigger different behaviour, while also maybe unwrapping it, so that the next filter is only dealing with the data payload, before another filter wraps the the data back before sending it on its way.

To provide a more concrete idea. Here's an example and user story of what I mean of how using a protocol as filter could look like. 

Imagine ACME broadcasting company is using SRT to broadcast video between their studios back to a control room, and from the control room to outside world to be retransmitted around the world. They want to send the data unencrypted when it's being sent internally between machines for speed, but when the control room is publicly transmitting it needs to be encrypted until it reaches the local broadcasters.

Here's how a filter chain could look with an SRT and match that would allow you to accept unencrypted SRT traffic, that is then rebroadcast as encrypted. You could of course write this whole thing in one filter, but I think this what a good filter chain could look like.

```yaml

version: v1alpha1
static:
  filters:
    # Parses and unwraps SRT data, populating metadata and session data with SRT headers.
    - name: acme.srt.unwrap
    - name: quilkin.match
      config:
        # Key to match against
        metadata: acme.srt.encryption
        # Match guard behaviour, whether to drop or pass if no arm matches.
        passthrough: pass
        # The list of values and filter chain arms.
        match_arms:
        - value: [AES-128, AES-192, AES-256]
          then:
           - name: quilkin.encryption
             config:
               # Maybe not this syntax, but we should have a syntax and mechanism for doing metadata substitution.
               algorithm: ${acme.srt.encryption} 
    # Uses Quilkin metadata to wrap the data back in an SRT packet.
    - name: acme.srt.wrap
```
