### ISSUE TITLE
Split filters into `read` and `write` branches in configuration.

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#637]
As I've been writing more complex filtering schemas the current single stream has struggle scaling. One example, is I have a protocol that goes through nine filters (through capturing, matching, and then using in something like TokenRouter) when reading packets from downstream, but only goes through one filter when writing data to downstream. This makes hard to see and reason with (should the write filter be at the top or bottom or in the middle, given that neither filters relate to each other and any position would be valid). This also simplifies filter configuration, as filters will no longer have to remember both their "read" version and "write" version of their config, instead they can have a single configuration that works for both cases.

I think we should split it into `filters.read` and `filters.write` to make it more clear what "stream" you're filtering at a given moment.

```yaml
filters:
  read:
      - name: quilkin.filters.capture.v1alpha1.Capture
        config:
          metadataKey: quilkin.dev/load_balancer/version
          suffix:
            size: 1
            remove: true
  write:
      - name: quilkin.filters.concatenate_bytes.v1alpha1.ConcatenateBytes
        config:
          strategy: Append
          bytes: [0, 0, 5, 5]
```
