### ISSUE TITLE
Add configuration for an instance to determine its health.

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#655]
We want to add a way for user's to configure whether certain performance metrics cause an instance to set itself to unhealthy so that it could automatically take itself out of rotation from selection.

I think just a new section in the admin configuration for setting these metrics. I'm not sure what's the best format for specifying these queries. My initial thought is that we could use PromQL queries against our metrics, as this would allow greater flexibility in how you define what causes the issue to be unhealthy, allows support of dynamic filter metrics, and PromQL already exists so there are [parser libraries](https://docs.rs/promql/latest/promql/index.html) for it already available, we'd just have to evaluate it (which could end up being a separate crate on its own that Quilkin uses).

```yaml
admin:
    health_thresholds:
          - rate(quilkin_packet_latency_seconds[5m]) > 15
          - rate(quilkin_errors_total[1m]) > 10
```
