### ISSUE TITLE
Replace `Config` with configuration components

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#700]
Currently we have the concept of a single "monolith" config file that's shared between all services from when there was only a proxy service. In its current form I don't find it to always to be clear when something is being shared and when something isn't, so I'd like to propose that we move away from the current configuration and instead create configuration files for specific components in Quilkin, this will make it easier to isolate and share specific parts of configuration without accidentally overriding another part of configuration, which also enables us to potentially have multiple configuration providers for different components to be running at once. It will also allow for the configuration to diverge from the schema of the current `Config` to be potentially more user-friendly.

A couple examples of component configuration that I think we should start with, namely ones for each service, and for `FilterChain` configuration. To be able to share code and make the configuration of each component more unified, I think we should adopt the same schema as Kubernetes CRDs, this would allow us to reuse more code for parsing, it's a format that people are already familiar with, and it allows for these components to potentially become CRD's down the line that can be discovered using a kubernetes configuration provider.

```yaml
version: quilkin.dev/v1alpha1
kind: Proxy
spec:
  filter_chain: acme.games/hello-world
  endpoints:
    - 192.168.0.1:8080
    - 192.168.0.1:8080
```

```yaml
version: quilkin.dev/v1alpha1
kind: ControlPlane
spec:
  provider:
    kind: Agones
    config_namespace: default
    gameserver_namespace: default

```

```yaml
version: quilkin.dev/v1alpha1
kind: Relay
spec:
  ads_port: 7800
  cpds_port: 7900
```

```yaml
version: quilkin.dev/v1alpha1
kind: FilterChain
metadata:
     id: acme.games/hello-world
spec:
  filters:
    - name: quilkin.filters.firewall.v1alpha1.Firewall
      config:
        on_read:
          - action: ALLOW
            source: 192.168.51.0/24
            ports:
              - 10
              - 1000-7000
        on_write: 
          - action: DENY
            source: 192.168.51.0/24
            ports:
              - 7000
```
