### ISSUE TITLE
List active sessions using the API

### ISSUE THREAD

**Issue by alt4** [googleforgames/quilkin#787]
Hello! I'm filling this issue as per my [conversation with Mark Mandel on Discord](https://discord.com/channels/773975408265134100/773975408856399894/1150110982518083695).

**Is your feature request related to a problem? Please describe.**

I am hosting a game that gets exposed to the Internet by Quilkin using the standard sidecar pattern on a generic k8s, with no Agones involved (yet?).
I happen to need to know the real client IP specific players use to connect to the game at a given moment.
This is far from easy at the moment since the game server only sees Quilkin's own IP. If I'm not mistaken, this IP is always 127.0.0.1 (due to the sidecar) for each players, but client port differs for each session.

**Describe the solution you'd like**

A `/sessions` API endpoint of sorts that would return currently active sessions with i.e.:
* The **real Client IP & Client Port**, which in my case would be the player's to Quilkin
* The **client port** (and possibly client IP?) **Quilkin allocates to that session** and uses to connect to the endpoint (game in my case)
would let me map the latter to the former directly from the game.
* The **endpoint's IP and port** Quilkin is proxying the client to (I wouldn't have much use for this myself having only one endpoint configured, but I suppose this could be useful otherwise)

I am not quite sure which format to use to return data would be optimal, but a simple JSON would likely work perfectly for me.

That endpoint may also be useful to troubleshoot specific sessions, and maybe provide additional session-specific data (i.e. lifetime, time since last packet transited or other metrics Quilkin might collect in the background).

**Describe alternatives you've considered**

N/A, though I am very much open to other solutions!

**Additional context**

Just in case, my current Quilkin config is as follow:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quilkin-sidecar-config
  labels:
    app: game
data:
  quilkin.yaml: |
    version: v1alpha1
    admin:
      address: "[::]:9091"
    id: game-proxy
    port: 8888
    clusters:
      default:
        localities:
          - endpoints:
              - address: 127.0.0.1:7777
```

And the container declaration in my kube manifest, alongside the game's container:

```yaml
[...]
      - name: quilkin
        image: us-docker.pkg.dev/quilkin/release/quilkin:0.5.0
        args: ["proxy"]
        ports:
        - name: proxy
          containerPort: 8888
          hostPort: 7777
          protocol: UDP
        livenessProbe:
          httpGet:
            path: /live
            port: 9091
          initialDelaySeconds: 3
          periodSeconds: 2
        resources:
          requests:
            memory: "128M"
            cpu: "0.25"
          limits:
            memory: "512M"
            cpu: "1"
        volumeMounts:
          - mountPath: /etc/quilkin/quilkin.yaml
            subPath: quilkin.yaml
            name: quilkin-config
            readOnly: true
[...]
```

Some more context is available in the Discord conversation linked at the top, but I am of course ready to provide more details if necessary :)
