### ISSUE TITLE
Proxy Static Configuration defaults to an empty HashMap when using HashedTokenRouter filter

### ISSUE THREAD

**Issue by jatin4sharma** [googleforgames/quilkin#958]
**What happened**: Lunched proxy with ["--config", "/etc/quilkin-proxy.yaml", "proxy"]

```
/etc/quilkin-proxy.yaml

version: v1alpha1
id: bigproxy
filters:
  - name: quilkin.filters.capture.v1alpha1.Capture
    config:
      suffix:
        size: 3
        remove: true
  - name: quilkin.filters.token_router.v1alpha1.HashedTokenRouter
clusters:
  - endpoints:
    - address: 10.9.140.85:7495
      metadata:
        quilkin.dev:
          tokens:
            - G6MF
```

Fired up client proxy with token "G6MF"
```
cat ~/lsg/client-token.yaml
version: v1alpha1
filters:
  - name: quilkin.filters.concatenate.v1alpha1.Concatenate
    config:
      on_read: APPEND
      on_write: DO_NOTHING
      bytes: G6MF
clusters:
  - endpoints:
    - address: 10.8.203.129:7777
```
Tried connecting via xonotic
```
kubectl logs -l role=proxy
{"timestamp":"2024-05-16T03:12:10.580209Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.9.0-dev","commit":"71ddf685948301f038c9e37c26f73362783c8058"},"target":"quilkin::cli","filename":"src/cli.rs","threadId":"ThreadId(1)"}
{"timestamp":"2024-05-16T03:12:12.313393Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::components::admin","filename":"src/components/admin.rs","threadId":"ThreadId(1)"}
{"timestamp":"2024-05-16T03:12:12.325402Z","level":"INFO","fields":{"message":"Starting proxy","port":7777,"proxy_id":"bigproxy"},"target":"quilkin::cli::proxy","filename":"src/cli/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2024-05-16T03:12:12.695266Z","level":"INFO","fields":{"message":"Quilkin is ready"},"target":"quilkin::components::proxy","filename":"src/components/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2024-05-16T03:12:12.695452Z","level":"INFO","fields":{"message":"starting phoenix HTTP service","addr":"[::]:7600"},"target":"quilkin::net::phoenix","filename":"src/net/phoenix.rs","threadId":"ThreadId(100)"}
{"timestamp":"2024-05-16T03:13:32.695401Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `G6MF` from `quilkin.dev/capture`","instances":"4"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(2)"}
{"timestamp":"2024-05-16T03:13:37.695843Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `G6MF` from `quilkin.dev/capture`","instances":"10"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(49)"}
{"timestamp":"2024-05-16T03:13:42.695357Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `G6MF` from `quilkin.dev/capture`","instances":"8"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(49)"}
{"timestamp":"2024-05-16T03:13:47.695735Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `G6MF` from `quilkin.dev/capture`","instances":"2"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(49)"}
```

**What you expected to happen**: Successful client connection to the endpoint

**How to reproduce it (as minimally and precisely as possible)**:  Launch quilkin [0.9.0-dev-4f3ca26](us-docker.pkg.dev/quilkin/ci/quilkin:0.9.0-dev-4f3ca26)
Fire it up with ["--config", "/etc/quilkin-proxy.yaml", "proxy"]
Fire up client proxy with token "G6MF"
Try connecting to the endpoint.

**Anything else we need to know?**: It seems the code only rebuilds the token_map if there is any changes incoming from the management_server(s) otherwise it will default to an empty HashMap.
Modifying [this](https://github.com/googleforgames/quilkin/blob/69fb369c388c54394cdaf9f227216fb633d607b1/src/net/cluster.rs#L113) function does the trick
```
    #[inline]
    pub fn new(endpoints: BTreeSet<Endpoint>) -> Self {
        let mut this = Self {
            endpoints,
            token_map: TokenAddressMap::new(),
            hash: 0,
            version: 0,
        };

        this.update();
        this.build_token_map(); <--------- add this line to rebuild the hashmap
        this
    }
```

**Environment**: DEV
- Quilkin version: 0.9.0-dev-4f3ca26
- Execution environment (binary, container, etc): container
- Operating system: Linux x86_64
- Custom filters? (Yes/No - if so, what do they do?): No
- Log(s):
- Others:
