### ISSUE TITLE
First connection to newly allocated gameserver using Proxy Dynamic Configuration with HashedTokenRouter filter is flaky

### ISSUE THREAD

**Issue by jatin4sharma** [googleforgames/quilkin#959]
**What happened**: Lunched proxy with ["proxy", "--management-server", "http://quilkin-relay-agones:7800"]
Allocated a game server
```
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
metadata:
  name: quilkin-gsa
  namespace: lsg
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: xonotic
  metadata:
    annotations:
      quilkin.dev/tokens: <<<<~52000 random Tokens generated via bash -c "openssl rand -base64 3">>>>>>
```
Querying the proxy admin endpoint confirms the endpoint and token exists.
```
kubectl -n lsg get po -l role=proxy -o json | jq .items[].status.podIP | xargs -I % curl -s %:8000/config | jq . | grep 94gk
                "94gk",
```
Fired up client proxy with token "94gk"
```
cat ~/lsg/client-token.yaml
version: v1alpha1
filters:
  - name: quilkin.filters.concatenate.v1alpha1.Concatenate
    config:
      on_read: APPEND
      on_write: DO_NOTHING
      bytes: 94gk
clusters:
  - endpoints:
    - address: 10.8.203.129:7777
```
Tried connecting via xonotic
```
kubectl logs -l role=proxy -f
{"timestamp":"2024-05-17T05:33:50.335504Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.9.0-dev","commit":"71ddf685948301f038c9e37c26f73362783c8058"},"target":"quilkin::cli","filename":"src/cli.rs","threadId":"ThreadId(1)"}
{"timestamp":"2024-05-17T05:33:50.335877Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::components::admin","filename":"src/components/admin.rs","threadId":"ThreadId(1)"}
{"timestamp":"2024-05-17T05:33:50.336040Z","level":"INFO","fields":{"message":"Starting proxy","port":7777,"proxy_id":"quilkin-proxies-58969c77b9-mgxcl"},"target":"quilkin::cli::proxy","filename":"src/cli/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2024-05-17T05:33:50.339590Z","level":"INFO","fields":{"message":"attempting to connect to `http://quilkin-relay-agones:7800/`"},"target":"quilkin::net::xds::client","filename":"src/net/xds/client.rs","threadId":"ThreadId(51)"}
{"timestamp":"2024-05-17T05:33:50.466335Z","level":"INFO","fields":{"message":"Connected to management server"},"target":"quilkin::net::xds::client","filename":"src/net/xds/client.rs","threadId":"ThreadId(51)"}
{"timestamp":"2024-05-17T05:33:50.647181Z","level":"INFO","fields":{"message":"Quilkin is ready"},"target":"quilkin::components::proxy","filename":"src/components/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2024-05-17T05:33:50.647551Z","level":"INFO","fields":{"message":"starting phoenix HTTP service","addr":"[::]:7600"},"target":"quilkin::net::phoenix","filename":"src/net/phoenix.rs","threadId":"ThreadId(150)"}
{"timestamp":"2024-05-17T05:36:10.647589Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `94gk` from `quilkin.dev/capture`","instances":"2"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(2)"}
{"timestamp":"2024-05-17T05:36:15.648252Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `94gk` from `quilkin.dev/capture`","instances":"10"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(2)"}
{"timestamp":"2024-05-17T05:36:20.648251Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `94gk` from `quilkin.dev/capture`","instances":"10"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(48)"}
{"timestamp":"2024-05-17T05:36:25.648016Z","level":"WARN","fields":{"message":"pipeline report","error":"filter  error: no endpoint matched token `94gk` from `quilkin.dev/capture`","instances":"2"},"target":"quilkin::components::proxy::packet_router","filename":"src/components/proxy/packet_router.rs","threadId":"ThreadId(2)"}
```

**What you expected to happen**: Successful client connection to the endpoint

**How to reproduce it (as minimally and precisely as possible)**: Launch quilkin [0.9.0-dev-4f3ca26](https://github.com/googleforgames/quilkin/issues/us-docker.pkg.dev/quilkin/ci/quilkin:0.9.0-dev-4f3ca26)
Fire it up with ["proxy", "--management-server", "http://quilkin-relay-agones:7800"]
Allocate a game server with a token
Wait for agones agent/relay to pass on the endpoint information to proxy.
Fire up client proxy with same token
Try connecting to the endpoint. <---------- **doesn't connect to the endpoint due to filter  error: no endpoint matched token**
Restart the proxy.
Try connecting to the endpoint. <---------- **this time the connection works**
Recreate(Delete/Create) the gameserver with a token
Fire up client proxy with same token
Try connecting to the endpoint. <---------- **doesn't connect to the endpoint due to filter  error: no endpoint matched token**

I have tried the same steps multiple times and it is the same behaviour every time.

**Anything else we need to know?**: 

**Environment**: DEV
- Quilkin version: 0.9.0-dev-4f3ca26
- Execution environment (binary, container, etc): k8s v1.28.8 / agones v1.39.0
- Operating system: Linux x86_64
- Custom filters? (Yes/No - if so, what do they do?): No
- Log(s):
- Others:
